-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-json
        files: \.(bowerrc|jshintrc|json)$
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        exclude: tests/acceptance/test_helper.py
    -   id: flake8
        args:
        - --max-line-length=82
        exclude: docs/source/conf.py
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
