#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *
from ttypes import *

CLIENT_SEND = 'cs'

CLIENT_RECV = 'cr'

SERVER_SEND = 'ss'

SERVER_RECV = 'sr'

